
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

import java_cup.runtime.*;
import java.util.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\073\000\002\002\004\000\002\002\004\000\002\002" +
    "\003\000\002\003\004\000\002\003\003\000\002\003\003" +
    "\000\002\003\003\000\002\003\003\000\002\003\005\000" +
    "\002\005\007\000\002\020\002\000\002\021\002\000\002" +
    "\006\012\000\002\007\004\000\002\007\002\000\002\022" +
    "\002\000\002\023\002\000\002\012\011\000\002\024\002" +
    "\000\002\012\012\000\002\025\002\000\002\026\002\000" +
    "\002\027\002\000\002\030\002\000\002\013\017\000\002" +
    "\011\005\000\002\011\005\000\002\011\005\000\002\011" +
    "\005\000\002\011\005\000\002\011\004\000\002\011\003" +
    "\000\002\011\005\000\002\011\003\000\002\011\003\000" +
    "\002\014\003\000\002\014\003\000\002\014\003\000\002" +
    "\015\003\000\002\015\005\000\002\015\004\000\002\016" +
    "\003\000\002\016\005\000\002\016\004\000\002\017\003" +
    "\000\002\017\005\000\002\017\004\000\002\010\005\000" +
    "\002\010\005\000\002\010\005\000\002\010\005\000\002" +
    "\010\005\000\002\010\005\000\002\010\005\000\002\010" +
    "\004\000\002\031\002\000\002\010\006\000\002\032\002" +
    "\000\002\010\006" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\163\000\034\004\013\006\016\007\007\010\024\011" +
    "\020\025\004\031\006\032\030\033\010\034\014\040\017" +
    "\044\015\045\032\001\002\000\020\025\004\031\006\032" +
    "\030\033\010\034\014\044\015\045\032\001\002\000\042" +
    "\012\uffdc\013\uffdc\015\uffdc\016\uffdc\017\uffdc\020\uffdc\022" +
    "\uffdc\023\uffdc\024\uffdc\025\uffdc\026\uffdc\027\uffdc\035\uffdc" +
    "\042\162\043\uffdc\045\163\001\002\000\042\012\uffdb\013" +
    "\uffdb\015\uffdb\016\uffdb\017\uffdb\020\uffdb\022\uffdb\023\uffdb" +
    "\024\uffdb\025\uffdb\026\uffdb\027\uffdb\035\uffdb\042\uffdb\043" +
    "\uffdb\045\uffdb\001\002\000\004\034\ufff2\001\002\000\042" +
    "\012\uffd8\013\uffd8\015\uffd8\016\uffd8\017\uffd8\020\uffd8\022" +
    "\uffd8\023\uffd8\024\uffd8\025\uffd8\026\uffd8\027\uffd8\035\uffd8" +
    "\042\uffd8\043\uffd8\045\uffd8\001\002\000\042\002\ufffb\004" +
    "\ufffb\005\ufffb\006\ufffb\007\ufffb\010\ufffb\011\ufffb\025\ufffb" +
    "\031\ufffb\032\ufffb\033\ufffb\034\ufffb\040\ufffb\041\ufffb\044" +
    "\ufffb\045\ufffb\001\002\000\014\024\037\025\036\026\040" +
    "\027\041\043\153\001\002\000\004\034\142\001\002\000" +
    "\020\025\004\031\006\032\030\033\010\034\014\044\015" +
    "\045\032\001\002\000\036\012\uffdf\013\uffdf\015\uffdf\016" +
    "\uffdf\017\uffdf\020\uffdf\022\uffdf\023\uffdf\024\uffdf\025\uffdf" +
    "\026\uffdf\027\uffdf\035\uffdf\043\uffdf\001\002\000\034\004" +
    "\uffef\006\uffef\007\uffef\010\uffef\011\uffef\025\uffef\031\uffef" +
    "\032\uffef\033\uffef\034\uffef\040\uffef\044\uffef\045\uffef\001" +
    "\002\000\034\004\013\006\016\007\007\010\024\011\020" +
    "\025\004\031\006\032\030\033\010\034\014\040\017\044" +
    "\015\045\032\001\002\000\004\034\124\001\002\000\042" +
    "\002\ufffc\004\ufffc\005\ufffc\006\ufffc\007\ufffc\010\ufffc\011" +
    "\ufffc\025\ufffc\031\ufffc\032\ufffc\033\ufffc\034\ufffc\040\ufffc" +
    "\041\ufffc\044\ufffc\045\ufffc\001\002\000\042\002\ufffd\004" +
    "\ufffd\005\ufffd\006\ufffd\007\ufffd\010\ufffd\011\ufffd\025\ufffd" +
    "\031\ufffd\032\ufffd\033\ufffd\034\ufffd\040\ufffd\041\ufffd\044" +
    "\ufffd\045\ufffd\001\002\000\042\012\uffdd\013\uffdd\015\uffdd" +
    "\016\uffdd\017\uffdd\020\uffdd\022\uffdd\023\uffdd\024\uffdd\025" +
    "\uffdd\026\uffdd\027\uffdd\035\uffdd\042\121\043\uffdd\045\122" +
    "\001\002\000\004\034\uffed\001\002\000\036\012\uffe2\013" +
    "\uffe2\015\uffe2\016\uffe2\017\uffe2\020\uffe2\022\uffe2\023\uffe2" +
    "\024\uffe2\025\uffe2\026\uffe2\027\uffe2\035\uffe2\043\uffe2\001" +
    "\002\000\036\002\051\004\013\006\016\007\007\010\024" +
    "\011\020\025\004\031\006\032\030\033\010\034\014\040" +
    "\017\044\015\045\032\001\002\000\042\012\uffde\013\uffde" +
    "\015\uffde\016\uffde\017\uffde\020\uffde\022\uffde\023\uffde\024" +
    "\uffde\025\uffde\026\uffde\027\uffde\035\uffde\042\046\043\uffde" +
    "\045\047\001\002\000\042\012\uffd5\013\uffd5\015\uffd5\016" +
    "\uffd5\017\uffd5\020\uffd5\022\uffd5\023\uffd5\024\uffd5\025\uffd5" +
    "\026\uffd5\027\uffd5\035\uffd5\042\uffd5\043\uffd5\045\uffd5\001" +
    "\002\000\042\002\ufffa\004\ufffa\005\ufffa\006\ufffa\007\ufffa" +
    "\010\ufffa\011\ufffa\025\ufffa\031\ufffa\032\ufffa\033\ufffa\034" +
    "\ufffa\040\ufffa\041\ufffa\044\ufffa\045\ufffa\001\002\000\040" +
    "\012\uffe0\013\uffe0\015\uffe0\016\uffe0\017\uffe0\020\uffe0\022" +
    "\uffe0\023\uffe0\024\uffe0\025\uffe0\026\uffe0\027\uffe0\030\034" +
    "\035\uffe0\043\uffe0\001\002\000\040\002\uffff\004\uffff\006" +
    "\uffff\007\uffff\010\uffff\011\uffff\025\uffff\031\uffff\032\uffff" +
    "\033\uffff\034\uffff\040\uffff\041\uffff\044\uffff\045\uffff\001" +
    "\002\000\020\025\004\031\006\032\030\033\010\034\014" +
    "\044\015\045\032\001\002\000\036\012\uffe1\013\uffe1\015" +
    "\uffe1\016\uffe1\017\uffe1\020\uffe1\022\uffe1\023\uffe1\024\037" +
    "\025\036\026\040\027\041\035\uffe1\043\uffe1\001\002\000" +
    "\020\025\004\031\006\032\030\033\010\034\014\044\015" +
    "\045\032\001\002\000\020\025\004\031\006\032\030\033" +
    "\010\034\014\044\015\045\032\001\002\000\020\025\004" +
    "\031\006\032\030\033\010\034\014\044\015\045\032\001" +
    "\002\000\020\025\004\031\006\032\030\033\010\034\014" +
    "\044\015\045\032\001\002\000\036\012\uffe5\013\uffe5\015" +
    "\uffe5\016\uffe5\017\uffe5\020\uffe5\022\uffe5\023\uffe5\024\uffe5" +
    "\025\uffe5\026\uffe5\027\uffe5\035\uffe5\043\uffe5\001\002\000" +
    "\036\012\uffe6\013\uffe6\015\uffe6\016\uffe6\017\uffe6\020\uffe6" +
    "\022\uffe6\023\uffe6\024\uffe6\025\uffe6\026\uffe6\027\uffe6\035" +
    "\uffe6\043\uffe6\001\002\000\036\012\uffe8\013\uffe8\015\uffe8" +
    "\016\uffe8\017\uffe8\020\uffe8\022\uffe8\023\uffe8\024\uffe8\025" +
    "\uffe8\026\040\027\041\035\uffe8\043\uffe8\001\002\000\036" +
    "\012\uffe7\013\uffe7\015\uffe7\016\uffe7\017\uffe7\020\uffe7\022" +
    "\uffe7\023\uffe7\024\uffe7\025\uffe7\026\040\027\041\035\uffe7" +
    "\043\uffe7\001\002\000\004\045\050\001\002\000\042\012" +
    "\uffd9\013\uffd9\015\uffd9\016\uffd9\017\uffd9\020\uffd9\022\uffd9" +
    "\023\uffd9\024\uffd9\025\uffd9\026\uffd9\027\uffd9\035\uffd9\042" +
    "\uffd9\043\uffd9\045\uffd9\001\002\000\042\012\uffda\013\uffda" +
    "\015\uffda\016\uffda\017\uffda\020\uffda\022\uffda\023\uffda\024" +
    "\uffda\025\uffda\026\uffda\027\uffda\035\uffda\042\uffda\043\uffda" +
    "\045\uffda\001\002\000\004\002\000\001\002\000\040\002" +
    "\001\004\001\006\001\007\001\010\001\011\001\025\001" +
    "\031\001\032\001\033\001\034\001\040\001\041\001\044" +
    "\001\045\001\001\002\000\004\034\054\001\002\000\020" +
    "\025\004\031\006\032\030\033\010\034\014\044\015\045" +
    "\032\001\002\000\014\024\037\025\036\026\040\027\041" +
    "\043\056\001\002\000\022\021\uffec\025\uffec\031\uffec\032" +
    "\uffec\033\uffec\034\uffec\044\uffec\045\uffec\001\002\000\022" +
    "\021\061\025\004\031\006\032\030\033\010\034\063\044" +
    "\015\045\032\001\002\000\026\012\077\013\102\015\103" +
    "\016\100\017\101\020\076\024\037\025\036\026\040\027" +
    "\041\001\002\000\022\021\061\025\004\031\006\032\030" +
    "\033\010\034\063\044\015\045\032\001\002\000\010\022" +
    "\066\023\067\043\112\001\002\000\022\021\061\025\004" +
    "\031\006\032\030\033\010\034\063\044\015\045\032\001" +
    "\002\000\030\012\077\013\102\015\103\016\100\017\101" +
    "\020\076\024\037\025\036\026\040\027\041\035\075\001" +
    "\002\000\010\022\066\023\067\035\070\001\002\000\022" +
    "\021\uffca\025\uffca\031\uffca\032\uffca\033\uffca\034\uffca\044" +
    "\uffca\045\uffca\001\002\000\022\021\uffc8\025\uffc8\031\uffc8" +
    "\032\uffc8\033\uffc8\034\uffc8\044\uffc8\045\uffc8\001\002\000" +
    "\012\022\uffcc\023\uffcc\035\uffcc\043\uffcc\001\002\000\022" +
    "\021\061\025\004\031\006\032\030\033\010\034\063\044" +
    "\015\045\032\001\002\000\012\022\uffc7\023\uffc7\035\uffc7" +
    "\043\uffc7\001\002\000\022\021\061\025\004\031\006\032" +
    "\030\033\010\034\063\044\015\045\032\001\002\000\012" +
    "\022\uffc9\023\uffc9\035\uffc9\043\uffc9\001\002\000\036\012" +
    "\uffe4\013\uffe4\015\uffe4\016\uffe4\017\uffe4\020\uffe4\022\uffe4" +
    "\023\uffe4\024\uffe4\025\uffe4\026\uffe4\027\uffe4\035\uffe4\043" +
    "\uffe4\001\002\000\020\025\004\031\006\032\030\033\010" +
    "\034\014\044\015\045\032\001\002\000\020\025\004\031" +
    "\006\032\030\033\010\034\014\044\015\045\032\001\002" +
    "\000\020\025\004\031\006\032\030\033\010\034\014\044" +
    "\015\045\032\001\002\000\020\025\004\031\006\032\030" +
    "\033\010\034\014\044\015\045\032\001\002\000\020\025" +
    "\004\031\006\032\030\033\010\034\014\044\015\045\032" +
    "\001\002\000\020\025\004\031\006\032\030\033\010\034" +
    "\014\044\015\045\032\001\002\000\022\022\uffd0\023\uffd0" +
    "\024\037\025\036\026\040\027\041\035\uffd0\043\uffd0\001" +
    "\002\000\022\022\uffd1\023\uffd1\024\037\025\036\026\040" +
    "\027\041\035\uffd1\043\uffd1\001\002\000\022\022\uffce\023" +
    "\uffce\024\037\025\036\026\040\027\041\035\uffce\043\uffce" +
    "\001\002\000\022\022\uffcf\023\uffcf\024\037\025\036\026" +
    "\040\027\041\035\uffcf\043\uffcf\001\002\000\022\022\uffd2" +
    "\023\uffd2\024\037\025\036\026\040\027\041\035\uffd2\043" +
    "\uffd2\001\002\000\022\022\uffcd\023\uffcd\024\037\025\036" +
    "\026\040\027\041\035\uffcd\043\uffcd\001\002\000\020\025" +
    "\uffeb\031\uffeb\032\uffeb\033\uffeb\034\uffeb\044\uffeb\045\uffeb" +
    "\001\002\000\020\025\004\031\006\032\030\033\010\034" +
    "\014\044\015\045\032\001\002\000\014\024\037\025\036" +
    "\026\040\027\041\035\115\001\002\000\034\004\uffea\006" +
    "\uffea\007\uffea\010\uffea\011\uffea\025\uffea\031\uffea\032\uffea" +
    "\033\uffea\034\uffea\040\uffea\044\uffea\045\uffea\001\002\000" +
    "\034\004\013\006\016\007\007\010\024\011\020\025\004" +
    "\031\006\032\030\033\010\034\014\040\017\044\015\045" +
    "\032\001\002\000\042\002\uffe9\004\uffe9\005\uffe9\006\uffe9" +
    "\007\uffe9\010\uffe9\011\uffe9\025\uffe9\031\uffe9\032\uffe9\033" +
    "\uffe9\034\uffe9\040\uffe9\041\uffe9\044\uffe9\045\uffe9\001\002" +
    "\000\012\022\uffcb\023\uffcb\035\uffcb\043\uffcb\001\002\000" +
    "\004\045\123\001\002\000\042\012\uffd3\013\uffd3\015\uffd3" +
    "\016\uffd3\017\uffd3\020\uffd3\022\uffd3\023\uffd3\024\uffd3\025" +
    "\uffd3\026\uffd3\027\uffd3\035\uffd3\042\uffd3\043\uffd3\045\uffd3" +
    "\001\002\000\042\012\uffd4\013\uffd4\015\uffd4\016\uffd4\017" +
    "\uffd4\020\uffd4\022\uffd4\023\uffd4\024\uffd4\025\uffd4\026\uffd4" +
    "\027\uffd4\035\uffd4\042\uffd4\043\uffd4\045\uffd4\001\002\000" +
    "\020\025\004\031\006\032\030\033\010\034\014\044\015" +
    "\045\032\001\002\000\014\024\037\025\036\026\040\027" +
    "\041\035\126\001\002\000\004\043\127\001\002\000\042" +
    "\002\ufff8\004\ufff8\005\ufff8\006\ufff8\007\ufff8\010\ufff8\011" +
    "\ufff8\025\ufff8\031\ufff8\032\ufff8\033\ufff8\034\ufff8\040\ufff8" +
    "\041\ufff8\044\ufff8\045\ufff8\001\002\000\036\004\013\006" +
    "\016\007\007\010\024\011\020\025\004\031\006\032\030" +
    "\033\010\034\014\040\017\041\131\044\015\045\032\001" +
    "\002\000\042\002\ufff9\004\ufff9\005\ufff9\006\ufff9\007\ufff9" +
    "\010\ufff9\011\ufff9\025\ufff9\031\ufff9\032\ufff9\033\ufff9\034" +
    "\ufff9\040\ufff9\041\ufff9\044\ufff9\045\ufff9\001\002\000\034" +
    "\004\013\006\016\007\007\010\024\011\020\025\004\031" +
    "\006\032\030\033\010\034\014\040\017\044\015\045\032" +
    "\001\002\000\004\007\134\001\002\000\004\034\135\001" +
    "\002\000\022\021\061\025\004\031\006\032\030\033\010" +
    "\034\063\044\015\045\032\001\002\000\010\022\066\023" +
    "\067\035\137\001\002\000\004\043\140\001\002\000\042" +
    "\002\uffee\004\uffee\005\uffee\006\uffee\007\uffee\010\uffee\011" +
    "\uffee\025\uffee\031\uffee\032\uffee\033\uffee\034\uffee\040\uffee" +
    "\041\uffee\044\uffee\045\uffee\001\002\000\014\024\037\025" +
    "\036\026\040\027\041\035\075\001\002\000\022\021\061" +
    "\025\004\031\006\032\030\033\010\034\063\044\015\045" +
    "\032\001\002\000\010\022\066\023\067\035\144\001\002" +
    "\000\034\004\ufff7\006\ufff7\007\ufff7\010\ufff7\011\ufff7\025" +
    "\ufff7\031\ufff7\032\ufff7\033\ufff7\034\ufff7\040\ufff7\044\ufff7" +
    "\045\ufff7\001\002\000\034\004\013\006\016\007\007\010" +
    "\024\011\020\025\004\031\006\032\030\033\010\034\014" +
    "\040\017\044\015\045\032\001\002\000\042\002\ufff6\004" +
    "\ufff6\005\ufff6\006\ufff6\007\ufff6\010\ufff6\011\ufff6\025\ufff6" +
    "\031\ufff6\032\ufff6\033\ufff6\034\ufff6\040\ufff6\041\ufff6\044" +
    "\ufff6\045\ufff6\001\002\000\042\002\ufff3\004\ufff3\005\151" +
    "\006\ufff3\007\ufff3\010\ufff3\011\ufff3\025\ufff3\031\ufff3\032" +
    "\ufff3\033\ufff3\034\ufff3\040\ufff3\041\ufff3\044\ufff3\045\ufff3" +
    "\001\002\000\042\002\ufff5\004\ufff5\005\ufff5\006\ufff5\007" +
    "\ufff5\010\ufff5\011\ufff5\025\ufff5\031\ufff5\032\ufff5\033\ufff5" +
    "\034\ufff5\040\ufff5\041\ufff5\044\ufff5\045\ufff5\001\002\000" +
    "\034\004\013\006\016\007\007\010\024\011\020\025\004" +
    "\031\006\032\030\033\010\034\014\040\017\044\015\045" +
    "\032\001\002\000\042\002\ufff4\004\ufff4\005\ufff4\006\ufff4" +
    "\007\ufff4\010\ufff4\011\ufff4\025\ufff4\031\ufff4\032\ufff4\033" +
    "\ufff4\034\ufff4\040\ufff4\041\ufff4\044\ufff4\045\ufff4\001\002" +
    "\000\042\002\ufffe\004\ufffe\005\ufffe\006\ufffe\007\ufffe\010" +
    "\ufffe\011\ufffe\025\ufffe\031\ufffe\032\ufffe\033\ufffe\034\ufffe" +
    "\040\ufffe\041\ufffe\044\ufffe\045\ufffe\001\002\000\004\034" +
    "\155\001\002\000\022\021\061\025\004\031\006\032\030" +
    "\033\010\034\063\044\015\045\032\001\002\000\010\022" +
    "\066\023\067\035\157\001\002\000\034\004\ufff1\006\ufff1" +
    "\007\ufff1\010\ufff1\011\ufff1\025\ufff1\031\ufff1\032\ufff1\033" +
    "\ufff1\034\ufff1\040\ufff1\044\ufff1\045\ufff1\001\002\000\034" +
    "\004\013\006\016\007\007\010\024\011\020\025\004\031" +
    "\006\032\030\033\010\034\014\040\017\044\015\045\032" +
    "\001\002\000\042\002\ufff0\004\ufff0\005\ufff0\006\ufff0\007" +
    "\ufff0\010\ufff0\011\ufff0\025\ufff0\031\ufff0\032\ufff0\033\ufff0" +
    "\034\ufff0\040\ufff0\041\ufff0\044\ufff0\045\ufff0\001\002\000" +
    "\004\045\164\001\002\000\042\012\uffd6\013\uffd6\015\uffd6" +
    "\016\uffd6\017\uffd6\020\uffd6\022\uffd6\023\uffd6\024\uffd6\025" +
    "\uffd6\026\uffd6\027\uffd6\035\uffd6\042\uffd6\043\uffd6\045\uffd6" +
    "\001\002\000\042\012\uffd7\013\uffd7\015\uffd7\016\uffd7\017" +
    "\uffd7\020\uffd7\022\uffd7\023\uffd7\024\uffd7\025\uffd7\026\uffd7" +
    "\027\uffd7\035\uffd7\042\uffd7\043\uffd7\045\uffd7\001\002\000" +
    "\036\012\uffe3\013\uffe3\015\uffe3\016\uffe3\017\uffe3\020\uffe3" +
    "\022\uffe3\023\uffe3\024\uffe3\025\uffe3\026\uffe3\027\uffe3\035" +
    "\uffe3\043\uffe3\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\163\000\030\002\025\003\032\005\021\006\020\011" +
    "\011\012\010\013\030\014\024\015\026\016\004\017\022" +
    "\001\001\000\014\011\164\014\024\015\026\016\004\017" +
    "\022\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\022\153\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\014\011\140\014\024" +
    "\015\026\016\004\017\022\001\001\000\002\001\001\000" +
    "\004\024\131\001\001\000\030\002\127\003\032\005\021" +
    "\006\020\011\011\012\010\013\030\014\024\015\026\016" +
    "\004\017\022\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\025\052\001" +
    "\001\000\002\001\001\000\026\003\051\005\021\006\020" +
    "\011\011\012\010\013\030\014\024\015\026\016\004\017" +
    "\022\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\014\011" +
    "\034\014\024\015\026\016\004\017\022\001\001\000\002" +
    "\001\001\000\014\011\044\014\024\015\026\016\004\017" +
    "\022\001\001\000\014\011\043\014\024\015\026\016\004" +
    "\017\022\001\001\000\014\011\042\014\024\015\026\016" +
    "\004\017\022\001\001\000\014\011\041\014\024\015\026" +
    "\016\004\017\022\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\014\011\054\014\024" +
    "\015\026\016\004\017\022\001\001\000\002\001\001\000" +
    "\004\026\056\001\001\000\016\010\061\011\057\014\024" +
    "\015\026\016\004\017\022\001\001\000\002\001\001\000" +
    "\016\010\117\011\057\014\024\015\026\016\004\017\022" +
    "\001\001\000\002\001\001\000\016\010\064\011\063\014" +
    "\024\015\026\016\004\017\022\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\031\072\001\001\000\004\032" +
    "\070\001\001\000\002\001\001\000\016\010\071\011\057" +
    "\014\024\015\026\016\004\017\022\001\001\000\002\001" +
    "\001\000\016\010\073\011\057\014\024\015\026\016\004" +
    "\017\022\001\001\000\002\001\001\000\002\001\001\000" +
    "\014\011\110\014\024\015\026\016\004\017\022\001\001" +
    "\000\014\011\107\014\024\015\026\016\004\017\022\001" +
    "\001\000\014\011\106\014\024\015\026\016\004\017\022" +
    "\001\001\000\014\011\105\014\024\015\026\016\004\017" +
    "\022\001\001\000\014\011\104\014\024\015\026\016\004" +
    "\017\022\001\001\000\014\011\103\014\024\015\026\016" +
    "\004\017\022\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\027\112\001\001\000\014\011\113" +
    "\014\024\015\026\016\004\017\022\001\001\000\002\001" +
    "\001\000\004\030\115\001\001\000\026\003\116\005\021" +
    "\006\020\011\011\012\010\013\030\014\024\015\026\016" +
    "\004\017\022\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\014\011\124\014\024\015\026\016\004\017\022\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\026\003\051\005\021\006\020\011\011\012\010\013\030" +
    "\014\024\015\026\016\004\017\022\001\001\000\002\001" +
    "\001\000\026\003\132\005\021\006\020\011\011\012\010" +
    "\013\030\014\024\015\026\016\004\017\022\001\001\000" +
    "\002\001\001\000\002\001\001\000\016\010\135\011\057" +
    "\014\024\015\026\016\004\017\022\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\016\010\142\011\057\014\024\015\026\016\004\017" +
    "\022\001\001\000\002\001\001\000\004\020\144\001\001" +
    "\000\026\003\145\005\021\006\020\011\011\012\010\013" +
    "\030\014\024\015\026\016\004\017\022\001\001\000\004" +
    "\021\146\001\001\000\004\007\147\001\001\000\002\001" +
    "\001\000\026\003\151\005\021\006\020\011\011\012\010" +
    "\013\030\014\024\015\026\016\004\017\022\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\016" +
    "\010\155\011\057\014\024\015\026\016\004\017\022\001" +
    "\001\000\002\001\001\000\004\023\157\001\001\000\026" +
    "\003\160\005\021\006\020\011\011\012\010\013\030\014" +
    "\024\015\026\016\004\017\022\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {



    // Variables globales
    private int var = 0;
    private int etq = 0;
    
    private Map<String,String> variablesDeclaradas = new HashMap<>();
    public int Borrar = 0;
    
    // Generadores de referencias
    /**
     * Genera una variable con la estructura '$vX', siendo X un número.
     */
    private String crearVariable() {
        return "$v" + (var++);
    }
    
    /**
     * Genera una etiqueta con la estructura 'EX', siendo X un número.
     */
    private String crearEtiqueta() {
        return "E" + (etq++);
    }
    
    
    // Generadores de código intermedio (.ctd)
    // ----------------------------------------------------------------------------------
    
    // Referencias
    public void variable(String variable, String valor) {
           PLXC.out.println("\t" + variable + " = " + valor + ";");  
    }

    public void SetVar(Variable a, String Tipo, String valor){
        a.setValor(valor);

        if(Tipo.equals("int")){
            a.setInt();
        }else if(Tipo.equals("float")){
            a.setFloat();
        }else if(Tipo.equals("char")){
            a.setChar();
        }
    }


    public void etiqueta(String etiqueta) {
         PLXC.out.println(etiqueta + ":");
    }
    
    public void salto(String etiqueta) {
        PLXC.out.println("\tgoto " + etiqueta + ";");
    }
    
    // Operdores
    public void suma(String variable, String a, String b) {
        PLXC.out.println("\t" + variable + " = " + a + " + " + b + ";");
    }
    
    public void resta(String variable, String a, String b) {
        PLXC.out.println("\t" + variable + " = " + a + " - " + b + ";");
    }
    
    public void producto(String variable, String a, String b) {
        PLXC.out.println("\t" + variable + " = " + a + " * " + b + ";");
    }
    
    public void division(String variable, String a, String b) {
        PLXC.out.println("\t" + variable + " = " + a + " / " + b + ";");
    }
    
    public void negativo(String variable, String a) {
        PLXC.out.println("\t" + variable + " = -" + a + ";");
    }
    
    // Funciones
    public void print(String argumento) {
        PLXC.out.println("\tprint " + argumento + ";");
    }
    
    public void ifMenor(String a, String b, String etiqueta) {
        PLXC.out.println("\tif (" + a + " < " + b + ") goto " + etiqueta + ";");
    }
    
    public void ifIgual(String a, String b, String etiqueta) {
        PLXC.out.println("\tif (" + a + " == " + b + ") goto " + etiqueta + ";");
    }


    // ----------------------------------------------------------------------------------
    /* Esta clase interna se encarga de almacenar 3 Parametros diferentes
     * de forma que puedan Asignarse Variables a Parametros a traves de Result
     * 
     */

    class Variable{

        private String tipo;
        private String var;
        private String valor;

        public Variable(){
            this.tipo = null;
            this.var = null;
            this.valor = null;

        }
        // SETTERS
        public void setInt(){
            this.tipo = "Int"; 
        }
        public void setChar(){
            this.tipo = "Char"; 
        }
        public void setFloat(){
            this.tipo = "float";
        }
        public void setVar(String variable){
            this.var = variable;
        }
        public void setValor(String valor){
            this.valor = valor; 
        }
        
        
        // GETTERS
         public String getInt(){
            return this.tipo;
        }
        public String getChar(){
            return this.tipo;
        }
        public String getFloat(){
            return this.tipo;
        }
        public String getVar( ){
            return this.var;
        }
        public String getValor(){
            return this.valor;
        }

    }




    // ----------------------------------------------------------------------------------
    /* Esta clase interna se encarga de almacenar 3 etiquetas diferentes
     * de forma que puedan moverse por la gramática a través de RESULT.
     * 
     * Las etiquetas representan lo siguiente:
     * 1. Salto si se cumple la condición (true).
     * 2. Salto si no se cumple la condición (false).
     * 3. Salto tras ejecutar la sentencia (salida).
     */

    class Condicion {
        
        // Variable
        private String[] etiquetas = {null, null, null};
        
        
        // Constructores
        public Condicion() {
            etiquetas[0] = crearEtiqueta();
            etiquetas[1] = crearEtiqueta();
        }
        
        public Condicion(String etiqueta1, String etiqueta2) {
            etiquetas[0] = etiqueta1;
            etiquetas[1] = etiqueta2;
        }
        
        
        // Getters
        public String etqTrue() {
            return etiquetas[0];
        }
        
        public String etqFalse() {
            return etiquetas[1];
        }
        
        public String etqSalida() {
            return etiquetas[2];
        }
        
        
        // Setters
        public void setEtqTrue(String etiqueta) {
            etiquetas[0] = etiqueta;
        }
        
        public void setEtqFalse(String etiqueta) {
            etiquetas[1] = etiqueta;
        }
        
        public void setEtqSalida(String etiqueta) {
            etiquetas[2] = etiqueta;
        }
    }

  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // sents ::= sents sent 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sents",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= sents EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // sents ::= sent 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sents",0, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // sent ::= exp PYC 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // sent ::= sent_print 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // sent ::= sent_if 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // sent ::= sent_while 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // sent ::= sent_for 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // sent ::= AL sents CL 
            {
              Object RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		  RESULT = s; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // sent_print ::= PRINT AP exp CP PYC 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		  RESULT = e;     print(e);   
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_print",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // NT$0 ::= 
            {
              Object RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Condicion c = (Condicion)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
Borrar++; System.out.println(Borrar);  c.setEtqSalida(crearEtiqueta());    etiqueta(c.etqTrue()); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$0",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // NT$1 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Condicion c = (Condicion)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
  salto(c.etqSalida());               etiqueta(c.etqFalse()); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$1",15, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // sent_if ::= IF AP cond CP NT$0 sent NT$1 sent_else 
            {
              Object RESULT =null;
              // propagate RESULT from NT$1
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		Condicion c = (Condicion)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		  etiqueta(c.etqSalida());                                    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_if",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // sent_else ::= ELSE sent 
            {
              Object RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		  RESULT = s; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_else",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // sent_else ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_else",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // NT$2 ::= 
            {
              String RESULT =null;
  RESULT = crearEtiqueta();   etiqueta(RESULT);       
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$2",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // NT$3 ::= 
            {
              String RESULT =(String) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Condicion c = (Condicion)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
  c.setEtqSalida(RESULT);     etiqueta(c.etqTrue());  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$3",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // sent_while ::= WHILE NT$2 AP cond CP NT$3 sent 
            {
              String RESULT =null;
              // propagate RESULT from NT$3
                RESULT = (String) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Condicion c = (Condicion)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		  salto(c.etqSalida());       etiqueta(c.etqFalse()); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_while",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // NT$4 ::= 
            {
              String RESULT =null;
  RESULT = crearEtiqueta();   etiqueta(RESULT);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$4",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // sent_while ::= DO NT$4 sent WHILE AP cond CP PYC 
            {
              String RESULT =null;
              // propagate RESULT from NT$4
                RESULT = (String) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-6)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Condicion c = (Condicion)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		  c.setEtqSalida(RESULT);     etiqueta(c.etqTrue());  salto(c.etqSalida());   etiqueta(c.etqFalse()); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_while",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // NT$5 ::= 
            {
              String RESULT =null;
  RESULT = crearEtiqueta();                                                   
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$5",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // NT$6 ::= 
            {
              String RESULT =(String) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
  etiqueta(RESULT);                                                           
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$6",20, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // NT$7 ::= 
            {
              String RESULT =(String) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Condicion c = (Condicion)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
  c.setEtqSalida(RESULT);     RESULT = crearEtiqueta();   etiqueta(RESULT);   
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$7",21, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // NT$8 ::= 
            {
              String RESULT =(String) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		Condicion c = (Condicion)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
  salto(c.etqSalida());       etiqueta(c.etqTrue());                          
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$8",22, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // sent_for ::= FOR NT$5 AP exp PYC NT$6 cond PYC NT$7 exp CP NT$8 sent 
            {
              String RESULT =null;
              // propagate RESULT from NT$8
                RESULT = (String) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).right;
		Condicion c = (Condicion)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-6)).value;
		  salto(RESULT);              etiqueta(c.etqFalse());              
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sent_for",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-12)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // exp ::= exp SUM exp 
            {
              String RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		  RESULT = crearVariable();   suma(RESULT, a, b);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // exp ::= exp RES exp 
            {
              String RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		  RESULT = crearVariable();   resta(RESULT, a, b);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // exp ::= exp MUL exp 
            {
              String RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		  RESULT = crearVariable();   producto(RESULT, a, b);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // exp ::= exp DIV exp 
            {
              String RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		  RESULT = crearVariable();   division(RESULT, a, b);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // exp ::= AP exp CP 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		  RESULT = e;                                         
              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // exp ::= RES exp 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		  RESULT = crearVariable();   negativo(RESULT, e);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // exp ::= Dec 
            {
              String RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Variable d = (Variable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // exp ::= VAR IGUAL exp 
            {
              String RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String v = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = crearVariable();  variable(v,e);  variable(RESULT,v);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // exp ::= VAR 
            {
              String RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String v = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = v;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // exp ::= NUM 
            {
              String RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = n;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // Dec ::= DecINT 
            {
              Variable RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Variable d = (Variable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Dec",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // Dec ::= DecFlo 
            {
              Variable RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Variable d = (Variable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Dec",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // Dec ::= DecChar 
            {
              Variable RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Variable d = (Variable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Dec",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // DecINT ::= INTE 
            {
              Variable RESULT =null;
		
              CUP$parser$result = parser.getSymbolFactory().newSymbol("DecINT",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // DecINT ::= DecINT COMA VAR 
            {
              Variable RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String v = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new Variable(); SetVar(RESULT,"int",v);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("DecINT",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // DecINT ::= DecINT VAR 
            {
              Variable RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String v = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new Variable(); SetVar(RESULT,"int",v);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("DecINT",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // DecChar ::= CH 
            {
              Variable RESULT =null;
		
              CUP$parser$result = parser.getSymbolFactory().newSymbol("DecChar",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // DecChar ::= DecChar COMA VAR 
            {
              Variable RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String v = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new Variable(); SetVar(RESULT,"char",v);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("DecChar",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // DecChar ::= DecChar VAR 
            {
              Variable RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String v = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new Variable(); SetVar(RESULT,"char",v);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("DecChar",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // DecFlo ::= FLO 
            {
              Variable RESULT =null;
		
              CUP$parser$result = parser.getSymbolFactory().newSymbol("DecFlo",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // DecFlo ::= DecFlo COMA VAR 
            {
              Variable RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String v = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new Variable(); SetVar(RESULT,"float",v);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("DecFlo",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // DecFlo ::= DecFlo VAR 
            {
              Variable RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String v = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new Variable(); SetVar(RESULT,"float",v);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("DecFlo",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // cond ::= exp EQ exp 
            {
              Condicion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		  RESULT = new Condicion();   ifIgual(a, b, RESULT.etqTrue());    salto(RESULT.etqFalse());   
              CUP$parser$result = parser.getSymbolFactory().newSymbol("cond",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // cond ::= exp NE exp 
            {
              Condicion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		  RESULT = new Condicion();   ifIgual(a, b, RESULT.etqFalse());   salto(RESULT.etqTrue());    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("cond",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // cond ::= exp LT exp 
            {
              Condicion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		  RESULT = new Condicion();   ifMenor(a, b, RESULT.etqTrue());    salto(RESULT.etqFalse());   
              CUP$parser$result = parser.getSymbolFactory().newSymbol("cond",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // cond ::= exp LE exp 
            {
              Condicion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		  RESULT = new Condicion();   ifMenor(b, a, RESULT.etqFalse());   salto(RESULT.etqTrue());    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("cond",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // cond ::= exp GT exp 
            {
              Condicion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		  RESULT = new Condicion();   ifMenor(b, a, RESULT.etqTrue());    salto(RESULT.etqFalse());   
              CUP$parser$result = parser.getSymbolFactory().newSymbol("cond",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // cond ::= exp GE exp 
            {
              Condicion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		  RESULT = new Condicion();   ifMenor(a, b, RESULT.etqFalse());   salto(RESULT.etqTrue());    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("cond",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // cond ::= AP cond CP 
            {
              Condicion RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Condicion c = (Condicion)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = c;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("cond",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // cond ::= NO cond 
            {
              Condicion RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Condicion c = (Condicion)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		  RESULT = new Condicion(c.etqFalse(), c.etqTrue());              
              CUP$parser$result = parser.getSymbolFactory().newSymbol("cond",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // NT$9 ::= 
            {
              Condicion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Condicion a = (Condicion)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
  etiqueta(a.etqTrue());                                          
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$9",23, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // cond ::= cond AND NT$9 cond 
            {
              Condicion RESULT =null;
              // propagate RESULT from NT$9
                RESULT = (Condicion) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Condicion a = (Condicion)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Condicion b = (Condicion)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		  etiqueta(a.etqFalse());     salto(b.etqFalse());    RESULT = b; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("cond",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // NT$10 ::= 
            {
              Condicion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Condicion a = (Condicion)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
  etiqueta(a.etqFalse());                                         
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$10",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // cond ::= cond OR NT$10 cond 
            {
              Condicion RESULT =null;
              // propagate RESULT from NT$10
                RESULT = (Condicion) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Condicion a = (Condicion)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Condicion b = (Condicion)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		  etiqueta(a.etqTrue());      salto(b.etqTrue());     RESULT = b; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("cond",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
